name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🛠 Maintenance'
    labels:
      - 'chore'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
template: |
  ## Changes

  $CHANGES

  ## Contributors

  Thanks to everyone who contributed to this release:
  $CONTRIBUTORS
